# Generated by Django 4.2 on 2023-04-19 04:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0013_alter_pokemon_date_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 4, 28, 49, 880167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='This is a pokemon of a certain pokemon type that will hopefully evolve', validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
