# Generated by Django 4.2 on 2023-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_alter_pokemon_date_captured'),
        ('trainer_app', '0003_trainer_name_trainer_pokemon_delete_master_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='pokemon',
            field=models.ManyToManyField(related_name='pokemon', to='pokemon_app.pokemon'),
        ),
    ]
