# Generated by Django 4.2 on 2023-04-20 15:55

import datetime
from django.db import migrations, models
import pokemon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_alter_pokemon_date_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 55, 32, 898563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[pokemon_app.validators.validate_name]),
        ),
    ]
