# Generated by Django 4.2.3 on 2023-07-14 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_app', '0001_initial'),
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(120)])),
                ('over_due_funds', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(related_name='members', to='book_app.book')),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.library')),
            ],
        ),
    ]
