# Generated by Django 4.2 on 2023-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_alter_pokemon_date_captured'),
        ('trainer_app', '0002_master_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='name',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon_app.pokemon'),
        ),
        migrations.DeleteModel(
            name='Master_Trainer',
        ),
    ]
