# Generated by Django 4.2 on 2023-04-14 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 5, 16, 41, 794654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='date_encountered',
            field=models.DateField(default='2008-01-01'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Unkown'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
