# Generated by Django 4.1.7 on 2023-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
        ('student_app', '0002_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='class_app.class'),
        ),
    ]
