# Generated by Django 4.2 on 2023-04-16 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_app', '0002_alter_move_name'),
        ('pokemon_app', '0011_alter_pokemon_date_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(default=[1], to='move_app.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 6, 35, 42, 80363, tzinfo=datetime.timezone.utc)),
        ),
    ]
