# Generated by Django 4.2 on 2023-04-16 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_alter_pokemon_date_captured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 5, 29, 23, 970315, tzinfo=datetime.timezone.utc)),
        ),
    ]
