# Generated by Django 4.2 on 2023-07-18 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_alter_pokemon_date_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Unknown', validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
