# Generated by Django 4.1.7 on 2023-04-25 15:49

import class_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, validators=[class_app.validators.validate_subject_format])),
                ('professor', models.CharField(max_length=255, validators=[class_app.validators.validate_professor_format])),
            ],
        ),
    ]
